create table Calendar_Event (
	uuid_ VARCHAR(75) null,
	eventId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	eventName VARCHAR(1000) null,
	startingDate DATE null,
	endingDate DATE null,
	timesAdditionalInfo STRING null,
	location VARCHAR(75) null,
	address VARCHAR(1000) null,
	imageUrl VARCHAR(1000) null,
	description STRING null,
	additionalInformation STRING null,
	signUpLink VARCHAR(1000) null,
	linkToEventWebPage VARCHAR(1000) null,
	categoryIds VARCHAR(75) null,
	eventAuthorName VARCHAR(75) null,
	eventAuthorEmail VARCHAR(75) null,
	eventAuthorPhoneNumber VARCHAR(75) null,
	additionalCompanyIds VARCHAR(500) null,
	status VARCHAR(75) null,
	authorizationToken VARCHAR(75) null,
	userGivenPassword VARCHAR(75) null,
	adminComment STRING null,
	showMap BOOLEAN,
	updateUrl VARCHAR(1000) null,
	eventFriendlyName VARCHAR(1000) null,
	additionalStartingDates STRING null,
	additionalStartingDatesRule VARCHAR(300) null
);